[package]
name = "mysk-lib-derives"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
darling.workspace = true
quote.workspace = true
syn.workspace = true
