[package]
name = "mysk-lib-macros"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
paste.workspace = true
sqlx.workspace = true
uuid.workspace = true
