[package]
name = "mysk-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version="4.3.1"}
env_logger = "0.10.0"
serde_qs= "0.12.0"
utoipa = { version = "3", features = ["actix_extras"] }
# openssl={ version = "0.10", features = ["v110"] }
sqlx = { version = "0.7.2", default-features = false, features = ["postgres", "uuid", "chrono", "json", "runtime-async-std-native-tls", "macros"] }
serde= "1.0.164"
serde_json = "1.0.64"
chrono = { version = "0.4.19", features = ["serde"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
base64 = "0.21.2"
jsonwebtoken = "8.3.0"
async-trait = "0.1.68"
